"""First migration

Revision ID: c8c5fe4ac917
Revises: 
Create Date: 2023-12-26 20:28:41.862055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8c5fe4ac917'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reminder',
    sa.Column('task_description', sa.String(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('remind_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('telegram_id', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('registered_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('last_channel_visit', sa.TIMESTAMP(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_id')
    )
    op.create_table('userreminder',
    sa.Column('users_id', sa.UUID(), nullable=False),
    sa.Column('reminder_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['reminder_id'], ['reminder.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['users_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('users_id', 'reminder_id', 'id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userreminder')
    op.drop_table('user')
    op.drop_table('reminder')
    # ### end Alembic commands ###
