version: '3.3'


services:
  bot:
    build: ./
    env_file: .env
    depends_on:
      - redis
      - postgres
  redis:
    image: "redis:6.2-alpine"
    restart: always
    volumes:
      - redis_data:/data
  postgres:
    image: "postgres:16"
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data


volumes:
  pg_data:
  redis_data:
